In [24]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
print(data)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]


In [25]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 

In [26]:
n_steps = 5
X, y = splitSequence(data, n_steps)

In [27]:
X

array([[ 10,  20,  30,  40,  50],
       [ 20,  30,  40,  50,  60],
       [ 30,  40,  50,  60,  70],
       [ 40,  50,  60,  70,  80],
       [ 50,  60,  70,  80,  90],
       [ 60,  70,  80,  90, 100],
       [ 70,  80,  90, 100, 110],
       [ 80,  90, 100, 110, 120],
       [ 90, 100, 110, 120, 130],
       [100, 110, 120, 130, 140],
       [110, 120, 130, 140, 150],
       [120, 130, 140, 150, 160],
       [130, 140, 150, 160, 170],
       [140, 150, 160, 170, 180],
       [150, 160, 170, 180, 190]])

In [28]:
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30 40 50] 60
[20 30 40 50 60] 70
[30 40 50 60 70] 80
[40 50 60 70 80] 90
[50 60 70 80 90] 100
[ 60  70  80  90 100] 110
[ 70  80  90 100 110] 120
[ 80  90 100 110 120] 130
[ 90 100 110 120 130] 140
[100 110 120 130 140] 150
[110 120 130 140 150] 160
[120 130 140 150 160] 170
[130 140 150 160 170] 180
[140 150 160 170 180] 190
[150 160 170 180 190] 200


In [29]:
X.shape

(15, 5)

In [30]:
from sklearn.model_selection import train_test_split
X_train_full, X_test, y_train_full, y_test = train_test_split(X,y, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full,y_train_full, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [31]:
X_train.shape

(8, 5)

In [32]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
# X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], n_features))
# X_valid = X_valid.reshape((X_valid.shape[0], X_valid.shape[1], n_features))
# X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], n_features))
# print(X_train[:2])

X = X.reshape((X.shape[0], X.shape[1], n_features))


In [33]:
X.shape

(15, 5, 1)

In [34]:
X[:2]

array([[[10],
        [20],
        [30],
        [40],
        [50]],

       [[20],
        [30],
        [40],
        [50],
        [60]]])

In [35]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [36]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [37]:
model.layers

In [38]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 50)                10400     
                                                                 
 dense_1 (Dense)             (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(),metrics=['accuracy'])

In [40]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 16188.8936 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 5ms/step - loss: 8738.2959 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 6ms/step - loss: 2312.3186 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 5ms/step - loss: 346.8190 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 7ms/step - loss: 301.6813 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 9ms/step - loss: 195.1428 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 5ms/step - loss: 110.2085 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 8ms/step - loss: 91.2654 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 6ms/step - loss: 177.0831 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 5ms/step - loss:

1/1 [==============================] - 0s 5ms/step - loss: 1.4139 - accuracy: 0.0000e+00
Epoch 81/200
1/1 [==============================] - 0s 5ms/step - loss: 2.4005 - accuracy: 0.0000e+00
Epoch 82/200
1/1 [==============================] - 0s 6ms/step - loss: 2.4374 - accuracy: 0.0000e+00
Epoch 83/200
1/1 [==============================] - 0s 5ms/step - loss: 1.3164 - accuracy: 0.0000e+00
Epoch 84/200
1/1 [==============================] - 0s 5ms/step - loss: 1.5975 - accuracy: 0.0000e+00
Epoch 85/200
1/1 [==============================] - 0s 6ms/step - loss: 2.2110 - accuracy: 0.0000e+00
Epoch 86/200
1/1 [==============================] - 0s 4ms/step - loss: 1.4970 - accuracy: 0.0000e+00
Epoch 87/200
1/1 [==============================] - 0s 5ms/step - loss: 1.2157 - accuracy: 0.0000e+00
Epoch 88/200
1/1 [==============================] - 0s 6ms/step - loss: 1.7323 - accuracy: 0.0000e+00
Epoch 89/200
1/1 [==============================] - 0s 7ms/step - loss: 1.5047 - accuracy: 0.00

1/1 [==============================] - 0s 7ms/step - loss: 0.0637 - accuracy: 0.0000e+00
Epoch 160/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0449 - accuracy: 0.0000e+00
Epoch 161/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0422 - accuracy: 0.0000e+00
Epoch 162/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0482 - accuracy: 0.0000e+00
Epoch 163/200
1/1 [==============================] - 0s 8ms/step - loss: 0.0433 - accuracy: 0.0000e+00
Epoch 164/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0456 - accuracy: 0.0000e+00
Epoch 165/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0469 - accuracy: 0.0000e+00
Epoch 166/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0316 - accuracy: 0.0000e+00
Epoch 167/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0377 - accuracy: 0.0000e+00
Epoch 168/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0325 - accur

In [41]:
test_data = np.array([90, 100, 110, 120, 130])
# test_data = test_data.reshape((1, n_steps, n_features))
# test_data

In [42]:
test_data.shape

(5,)

In [43]:
# EPOCHS = 500

# history = model.fit(X_train, y_train, epochs=EPOCHS, validation_data=(X_valid, y_valid))

In [44]:
# predictNextNumber = model.predict(scaler.transform([test_data]).reshape((1, n_steps, n_features)), verbose=1)
# print(predictNextNumber)

In [45]:
test_data = np.array([160, 170, 180, 190, 200])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[160],
        [170],
        [180],
        [190],
        [200]]])

In [46]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 168ms/step
[[210.57683]]
