1. Write a Python Program to Add Two Matrices?

In [42]:
def add_mat(mat1,mat2):
    import numpy as np
    mat1=np.array(mat1)
    mat2=np.array(mat2)
    sum=np.zeros( mat1.shape)
    
    if mat1.shape != mat2.shape:
        return "Please enter matrixes of same shape"
    else:
        for i in range(mat1.shape[0]):
            for j in range(mat1.shape[1]):
                  sum[i][j]=mat1[i][j]+mat2[i][j]
        return sum
        
        

In [45]:
mat1=[[1,2],
     [1,2]]
mat2=[[1,2],
     [1,0]]
add_mat(mat1,mat2)

array([[2., 4.],
       [2., 2.]])

In [14]:
def mul_mat(mat1,mat2):
    import numpy as np
    mat1=np.array(mat1)
    mat2=np.array(mat2)
    mul=np.zeros( (mat1.shape[0],mat2.shape[1]))
    
    if mat1.shape[0]!=mat2.shape[1]:
        return "Please enter matrixes of correct shape"
    else:   
        for i in range(mat1.shape[0]):
            for j in range(mat2.shape[1]):
                for k in range(mat2.shape[0]):
                    mul[i][j]+=mat1[i][k]*mat2[k][j]
            
            
                    
        return mul

In [15]:
mul_mat([[1,3,5],
        [3,4,6]],
       [[4,0],
       [2,1],
       [1,5]])

array([[15., 28.],
       [26., 34.]])

In [17]:
def mat_transpose(mat):
    import numpy as np
    mat=np.array(mat)
    tra=np.zeros( (mat.shape[1],mat.shape[0]))
    
    for i in range(mat.shape[1]):
        for j in range(mat.shape[0]):
            tra[i][j]=mat[j][i]
    
    return tra
    
    

In [18]:
mat_transpose([[1,3,5],
        [3,4,6]])

array([[1., 3.],
       [3., 4.],
       [5., 6.]])

In [40]:
# To take input from the user
def sort_words(str):
    sort=''
    words = [word.lower() for word in str.split()]
    words.sort()
    
    
    sort=' '.join(words)
    return sort

In [41]:
sort_words('Write a Python Program to Sort Words in Alphabetic Order')

'a alphabetic in order program python sort to words write'

In [43]:
def remove_punc(str):
    import string
    exclude = set(string.punctuation)
    new = ''.join(ch for ch in str if ch not in exclude)
    return new

In [45]:
remove_punc('5. Write a@ Python Program, to Remove !Punctuation From a String?')

'5 Write a Python Program to Remove Punctuation From a String'