In [2]:
import numpy as np
np_arr = np.empty(3, dtype=int) 
np_arr
# The output shows that np_arr contains 3 random integer values(because the resultant array is uninitialized).

array([7536757, 6029426, 6881378])

In [3]:
np_arr = np.zeros(5) 
np_arr

array([0., 0., 0., 0., 0.])

In [8]:
np_arr = np.ones((2, 2), dtype=float) 
np_arr

array([[1., 1.],
       [1., 1.]])

In [9]:
np_arr+1.5

array([[2.5, 2.5],
       [2.5, 2.5]])

In [10]:
np_arr*=1.5
np_arr

array([[1.5, 1.5],
       [1.5, 1.5]])

In [22]:
import numpy as np
  
# Create the numpy array
country = np.array(['USA', 'Japan', 'UK', '', 'India', 'China'])
  
# Print the array
print(country)

['USA' 'Japan' 'UK' '' 'India' 'China']


In [23]:

# Assign 'New Zealand' at the place of missing value
country[country == ''] = 'New Zealand'
  
# Print the modified array
print(country)

['USA' 'Japan' 'UK' 'New Z' 'India' 'China']


In [24]:
import statistics

sample = [1,2,3,4,5,5,5,5,10]
standard_deviation = statistics.stdev(sample)
print(standard_deviation)

2.5549516194593154


In [ ]:
Using Numpy to Calculate Standard Deviation
Numpy has a function named np.std(), which is used to calculate the standard deviation of a sample. The function uses the following syntax:

np.std(
   [data],   # The data to use
   ddof=1    # The degrees of freedom to use
)

In [25]:
import numpy as np

sample = [1,2,3,4,5,5,5,5,10]
standard_deviation = np.std(sample, ddof=1)
print(standard_deviation)

2.5549516194593154


In [26]:
import pandas as pd

dataframe_dictionary = {
   'Name': ['John', 'Meaghan', 'Kate', 'Peter', 'Jane'], 
   'Height': [170,155,160,185,145], 
   'Weight': [160, 120, 125, 200, 135]
}

df = pd.DataFrame(data = dataframe_dictionary)
standard_deviation = df.std()

print(standard_deviation)

Height    15.247951
Weight    32.901368
dtype: float64


C:\Users\prakh\AppData\Local\Temp/ipykernel_17684/2948612296.py:10: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  standard_deviation = df.std()
